### ISSUE TITLE
Il manque quelques couches graphiques

### ISSUE THREAD

**Issue by AlainFELER** [ThomasG77/telepac-script-parser#2]
J'ai fait un test sur un fichier 2016, 2017, 2022 et 2023. Ca ne marche plus que pour 2023 (la version du 12/1 fonctionnait pour le fichier 2022 fourni par map), mais je ne sais pas si c'est important pour quelqu'un.

Plus important : le programme omet les géométries des MAEC ponctuelles, linéaires, et surfaciques <elements-maec-S> ou -L ou -P (mais il n'y a que des -S dans le fichier xml 2023 fourni et rien dans le 2022), et les éléments bio (mais il n'y en a pas dans le xml 2023 ni dans le 2022).

Désolé pour l'échantillon de test réduit... je vais demander à la personne s'il peut en fournir d'autres.

En 2017, j'avais pu traiter 6000 fichiers, c'est mieux pour trouver plus de cas de figure !

Ci-dessous les traces d'exécution :
```
C:\z\t2016>python ..\read_pac_xml.py Dossier-PAC-2016_dossier_029000144_20170925104624.xml
Traceback (most recent call last):
  File "..\read_pac_xml.py", line 91, in <module>
    courriel = demandeur.find('courriel').text
AttributeError: 'NoneType' object has no attribute 'text'

C:\z\t2017>python ..\read_pac_xml.py Dossier-PAC-2017_dossier_029000426_20170713161751.xml
Traceback (most recent call last):
  File "..\read_pac_xml.py", line 91, in <module>
    courriel = demandeur.find('courriel').text
AttributeError: 'NoneType' object has no attribute 'text'

C:\z\t2022>python ..\read_pac_xml.py Dossier-PAC-2022_dossier_012000001_20220000000008.xml
Traceback (most recent call last):
  File "..\read_pac_xml.py", line 347, in <module>
    fc = csv.DictWriter(outfile, fieldnames=v[0].keys())
AttributeError: 'list' object has no attribute 'keys'

C:\z\t2023>python ..\read_pac_xml.py dossier_test_2023.xml

C:\z\t2023>
```
Cordialement,
AF

**Comment by AlainFELER** [comment]
Encore zut, comme j'ai mis des `` ça a omis elements-maec-S 
dans la ligne
Plus important : le programme omet les géométries des MAEC ponctuelles, linéaires, et surfaciques elements-maec-S ou -L ou -P
